name: Create the dev staging environment

on:
  workflow_dispatch:
    inputs:
      PR_number:
        description: "The PR number"
        required: true

defaults:
  run:
    shell: bash
    working-directory: infra

jobs:
  create:
    runs-on: ubuntu-latest
    steps:
      #   - name: Checkout code
      #     uses: actions/checkout@v2

      #   - name: Set up Node.js
      #     uses: actions/setup-node@v2
      #     with:
      #       node-version: 21

      #   - name: Install dependencies
      #     run: npm ci

      - name: Use github script
        uses: actions/github-script@v5
        id: hello_github_script
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          result-encoding: string
          script: |
            const output = `
              this comment comes from github script.\n
              owner: ${context.repo.owner}\n
              repo: ${context.repo.repo}\n
              issue_number: \`${{github.event.inputs.PR_number}}\`
            `
            github.rest.issues.createComment({
              owner: context.repo.owner,
              repo: context.repo.repo,
              issue_number: ${{ github.event.inputs.PR_number }},
              body: output
            });
