name: GitHub Actions Build and Deploy Demo
on:
  push:
    branches:
      - main
    paths:
      - "web/**"
  workflow_dispatch:

defaults:
  run:
    shell: bash
    working-directory: web

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 21
      - name: Checkout
        uses: actions/checkout@v4
      - name: Install and Build
        run: |
          npm install
          npm run build
      - name: Deploy
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          folder: web/dist
          branch: gh-pages
